<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKnD1ViG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKnD1ViG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKnD1ViG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKnD1ViG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKnD1ViG\App_KernelDevDebugContainer([
    'container.build_hash' => 'KnD1ViG',
    'container.build_id' => '430c2092',
    'container.build_time' => 1726761910,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKnD1ViG');
