<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

use Container1K2FCBC\App_KernelDevDebugContainer;

if (\class_exists(\Container1K2FCBC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1K2FCBC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1K2FCBC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1K2FCBC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1K2FCBC\App_KernelDevDebugContainer([
    'container.build_hash' => '1K2FCBC',
    'container.build_id' => '5c18c0a9',
    'container.build_time' => 1726767816,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container1K2FCBC');
